update mac - generic dmg installer
TheJumpCloud/support pull request #498
Opened 2023-06-07 20:48 UTC by kmaranionjc

## Issues
* [SA-3359](https://jumpcloud.atlassian.net/browse/<jira-id>) - SA-3359

## What does this solve?
Update mac generic dmg installer to fix error issues.

## Is there anything particularly tricky?
n/a
## How should this be tested?
Test with with a direct download link stored in S3 or links you're able to directly download from a website.

## Screenshots

2023-06-07 21:36 UTC, jworkmanjc requested changes
I'm fine with these changes, it's more proper bash according to my bash linter. Tested with chrome/ slack and both these DMGs extract and install correctly. 

I'm game to merge this in if we bump the version and delineate between the script variables and the script contents.

2023-06-07 21:36 UTC, jworkmanjc commented on PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Generic DMG Installer.md
>  # *** USAGE *** Version: 1.1
We should bump this version to 1.2 just to note a change

2023-06-07 21:36 UTC, jworkmanjc commented on PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Generic DMG Installer.md
> -### Modify below this line at your own risk!
I think we should keep this line just to break up the script from what we want them to change

2023-06-08 04:01 UTC, aguzmanjc approved these changes

2023-06-08 18:12 UTC, gweinjc approved these changes

2023-06-08 20:40 UTC, merged