SA-3607: PSModule Release GitHub Actions Workflow
TheJumpCloud/support pull request #529
Opened 2023-10-11 20:47 UTC by gweinjc

## Issues
* [SA-3607](https://jumpcloud.atlassian.net/browse/SA-3607) - PSModule Release GitHub Actions Workflow

## What does this solve?
With the migration from CircleCI to GitHub Actions, we need to transfer our Release workflow into GHA. This workflow will allow us to release new versions of the PowerShell module provided that certain criteria are met.

### Criteria to allow a PowerShell release:
- Pull Request is merged into `master` branch
- Files that were changed were located in the following paths:
    - `"PowerShell/Deploy/**"`
    - `"PowerShell/JumpCloud Module/**"`
    - `"PowerShell/ModuleChangelog.md"`
- The Pull Request is labeled with the `PowerShell Module` label

### Jobs and their function
- `Check-If-Merged`: Validates that the Pull Request was actually merged into Master. If the Pull Request was just closed, we do not want to start a release off of this action.
- `Filter-Branch`: Validates that the PR has PowerShell Module label
- `Check-PR-Label`: Also validates the PR has PowerShell Module label
- `Setup-Build-Dependancies`: Installs required modules for PowerShell release and caches for use in a later job
- `Manual-Approval-Release`: Using the environment `PublishToPSGallery`, all required reviewers will get a notification to approve the workflow to continue with the deployment, otherwise it will timeout or we can manually cancel the workflow in case of accidental release
- `Draft-GH-Release`: Drafts a PowerShell module release using the GitHub Release API/CLI
- `Deploy-Nupkg`: Performs the deployment to PSGallery
- `Cleanup-Cache`: Cleans up any leftover caches from previous runs, this will eliminate any unnecessary resources being used

## Is there anything particularly tricky?
We cannot really test this workflow without intending to release anything.
We do not have CodeArtifact accounted for in this version of the workflow

## How should this be tested?
N/A

2023-10-11 21:36 UTC, jworkmanjc requested changes
I'm good to merge in w/ removal of extra dependancies. At this stage nothing in our Release CI workflow requires:
SDKs.
PSScriptAnalyzer
PlatPS

2023-10-11 21:36 UTC, jworkmanjc commented on .github/workflows/release-workflow.yml
> +              'JumpCloud.SDK.DirectoryInsights'       = @{Repository = 'PSGallery'; RequiredVersion = '0.0.23'}
Eventually, this doesn't have to be today but I think we can keep the SDK releases on latest. I'm not sure they are even required for our Release Pipeline...

I'm pretty sure all were need here is the AWS tools, nuget & powerShellGet

2023-10-11 21:36 UTC, jworkmanjc commented on .github/workflows/release-workflow.yml
> +          dotnet nuget add source "https://www.powershellgallery.com/api/v2/package" --name PSGallery
Nuget is already installed so nice, no need to re-install 
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

2023-10-11 21:43 UTC, jworkmanjc commented on .github/workflows/release-workflow.yml
> +              'JumpCloud.SDK.DirectoryInsights'       = @{Repository = 'PSGallery'; RequiredVersion = '0.0.23'}
We are going to try the cache on merge

2023-10-11 21:43 UTC, jworkmanjc approved these changes
Approved, we'll attempt a release tomorrow

2023-10-12 13:58 UTC, kmaranionjc approved these changes

2023-10-12 16:02 UTC, merged