Build Module Helpfiles, Pestertestfiles, and Changelog versioning tool
TheJumpCloud/support pull request #549
Opened 2023-12-05 21:45 UTC by kmaranionjc

## Issues
* [SA-3705-Build-Module-Function](https://jumpcloud.atlassian.net/browse/SA-3705) - SA-3705-Build-Module-Function

## What does this solve?
This tool fixes the issue with the change from CircleCI to GHA migration where we are unable to write back our automations with building module, help and test files, and changelog edits. This process is now done locally with this change.
## Is there anything particularly tricky?
N/A
## How should this be tested?
1. Run `."PowerShell/Deploy/Build-Module.ps1" -releasetype major `  

- Test out different release type
2. Validate changelog changes

- Change current version date to different date
- Rerun Build-Module
- Validate that the date is today's date 
3. Validate JumpCloud.psd1 changes (date, version)

2023-12-06 21:27 UTC, jworkmanjc commented on PowerShell/Deploy/Build-Module.ps1
>      [String]
It would be nice to automatically prompt for this value if not specified + add a validate set

2023-12-06 21:29 UTC, jworkmanjc commented on PowerShell/Deploy/Build-Module.ps1
> +."$PSScriptRoot/Build-HelpFiles.ps1" -ModuleName "JumpCloud" -ModulePath "./PowerShell/JumpCloud Module"
```suggestion
."$PSScriptRoot/Build-HelpFiles.ps1" -ModuleName "JumpCloud" -ModulePath (Get-Item -Path:($FilePath_psd1)).directory
```

2023-12-06 21:31 UTC, jworkmanjc commented on PowerShell/Deploy/Build-Module.ps1
> +."$PSScriptRoot/Build-HelpFiles.ps1" -ModuleName "JumpCloud" -ModulePath "./PowerShell/JumpCloud Module"
Depending on where you call this function, It'll throw errors, I want this to be as simple as possible, if we sub a variable for a hard-coded path, it'll be more likely to work when called from different working dirs.

2023-12-06 21:51 UTC, jworkmanjc requested changes
I ran this from another directory and the script threw an error. I think you addressed that in the time before I was able to write the review but yes this does what the card requires. The only other item I want to see here is a mandatory param set for the `$releaseType` and a validate set to ensure someone who hasn't used this knows what the valid values are.

2023-12-07 15:37 UTC, jworkmanjc approved these changes
Thanks for the changes! Looks good and is working in my testing!

2023-12-08 15:23 UTC, gweinjc approved these changes

2023-12-12 20:12 UTC, merged