BAN-2126: Changes to Linux RAA install script
TheJumpCloud/support pull request #556
Opened 2024-01-19 11:07 UTC by asinghjc

## Issues
* [BAN-2126](https://jumpcloud.atlassian.net/browse/BAN-2126) - Changes to Linux RAA install script

## What does this solve?

## Is there anything particularly tricky?

## How should this be tested?

## Screenshots

2024-01-19 19:52 UTC, gweinjc approved these changes
Tested good on my end

2024-01-19 20:16 UTC, kmaranionjc approved these changes

2024-01-19 20:34 UTC, jworkmanjc requested changes
When running this command, I copy the entire script contents from the command body window. Paste into JumpCloud Command and execute the script on a device. 

First time this is run I get an "exit 0" status and note that `raa_version' need to be provided in the script (eg. v0.75.0)` — which in my opinion is incorrect. It should be exit 1 if a customer sees this. 

I'd imagine that customers have no clue what version they need to specify here. Is there a list of available somewhere that we can reference or can I just type v2.23.4 and hope for the best? 

- Script should throw exit 1 instead on line 22

Additionally after specifying the version suggested in the command the script returns an exit code: 1 noting: 
```
x86_64 
bash: line 37: raa_directory: unbound variable
```

- Unsure how to address this error

2024-01-19 20:34 UTC, jworkmanjc commented on PowerShell/JumpCloud Commands Gallery/commands.json
>      "description": "This script installs rempte assist application on the Linux machine."
```suggestion
    "description": "This script installs remote assist application on the Linux machine."
```

2024-01-26 20:09 UTC, jworkmanjc approved these changes
Okay tested again! Now it's working I wish there was a way to always pull in the latest version of the APP instead of having the customer write to line 29 but I do see that the script is installing the RAA app now. Approved

2024-01-26 21:51 UTC, kmaranionjc approved these changes
Installed worked good on my end. Only is is the RAA version as per my comment.

2024-01-26 21:51 UTC, kmaranionjc commented on PowerShell/JumpCloud Commands Gallery/Linux Commands/Linux - remote-assist - Installation script.md
> +# the example format of version: v0.172.0
This would be nice automated. I can see customers being confused on what the current version is.

2024-01-29 15:38 UTC, merged