Removing installRemoteAssist.sh as not required in public repo
TheJumpCloud/support pull request #562
Opened 2024-02-20 10:34 UTC by mkhopde

## Issues
* [<jira-id>](https://jumpcloud.atlassian.net/browse/<jira-id>) - <jira-title>

## What does this solve?

## Is there anything particularly tricky?

## How should this be tested?

## Screenshots

2024-02-23 16:23 UTC, jworkmanjc approved these changes

2024-02-23 17:25 UTC, kmaranionjc approved these changes

2024-02-23 18:00 UTC, jworkmanjc requested changes
We need to commit the changes to `commands.json` I'll push an update in one moment

2024-02-23 21:36 UTC, jworkmanjc commented
Do we need to remove the Linux remote assist scripts located at : https://github.com/TheJumpCloud/support/blob/master/PowerShell/JumpCloud%20Commands%20Gallery/Linux%20Commands/Linux%20-%20remote-assist%20-%20Installation%20script.md
@mkhopde

2024-03-04 14:10 UTC, jworkmanjc approved these changes

2024-03-04 16:42 UTC, kmaranionjc approved these changes

2024-03-04 23:07 UTC, merged