Cut 4251 remove attribute parameter not working
TheJumpCloud/support pull request #596
Opened 2024-08-16 22:08 UTC by kmaranionjc

## Issues
* [Cut 4251](https://jumpcloud.atlassian.net/browse/Cut 4251) - Cut 4251

## What does this solve?
Rename -RemoveAttribute to -RemoveCustomAttribute
## Is there anything particularly tricky?
n/a
## How should this be tested?
Import this branch module then run:
Create a custom attribute: 
`Set-JCUser -Username YOURUSER -NumberOfCustomAttributes 1 -Attribute1_name 'NewAttribute' -Attribute1_value 'IT'`
Remove the created attribute from above:
`Set-JCUser YOURUSER -RemoveCustomAttribute NewAttribute`

## Screenshots

2024-08-19 17:56 UTC, jworkmanjc submitted a review, later dismissed

2024-08-20 15:42 UTC, gweinjc requested changes

2024-08-20 15:42 UTC, gweinjc commented on PowerShell/JumpCloud Module/Docs/Set-JCUser.md
>  This example removes the Custom Attribute with the name 'Department' from all JumpCloud Users in the JumpCloud User Group 'Sales'
This example text doesn't match what the function is doing

2024-08-20 20:39 UTC, jworkmanjc approved these changes

2024-08-20 20:45 UTC, gweinjc approved these changes

2024-08-20 20:54 UTC, merged