Updated saves to more secure locations, reorganized checks and fixed …
TheJumpCloud/support pull request #598
Opened 2024-08-23 18:19 UTC by tschuttjc

…couple typos.

## Issues
* [SUP-1351]https://jumpcloud.atlassian.net/browse/SUP-1451 - log collect - secure collected files and written archive

## What does this solve?
Resolves some concerns from security about target directory for collected archive.
Reorganizes some prereq checks
skips runs which require an active user session
Fixed a typo for stderr/stdout redirection.

## Is there anything particularly tricky?
Not really....

## How should this be tested?
Two separate runs from JC Commands:
1) with active user session on macOS device - verify written to user's ~/Documents folder
2) with device sitting at login window / no active user session - verify archive written to /var/tmp/ 

## Screenshots

2024-08-26 23:06 UTC, kmaranionjc commented
@tschuttjc ran the command with active user successfully. Was able to get the logs with no active user session but I got an error in the end of it (refer to screenshot). 
<img width="961" alt="image" src="https://github.com/user-attachments/assets/411608c2-c271-45cb-9975-79a8fbafa608">

2024-08-26 23:08 UTC, kmaranionjc requested changes

2024-08-26 23:08 UTC, kmaranionjc commented on scripts/macos/log_collection.sh
> +You may run the command `open /var/tmp` in the macOS Terminal to do this."
Syntax error here,  looks like `open /var/tmp`  is not being outputted

2024-08-29 19:19 UTC, kmaranionjc approved these changes
Awesome work here @tschuttjc! Thanks for the changes. 
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/7e736eac-4e06-4589-b8fa-25c02e85206e">
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/5c7c5aeb-c794-405e-a19e-0b0a58d2f37e">

2024-08-29 19:21 UTC, jworkmanjc approved these changes

2024-08-29 19:34 UTC, merged